# target namespace
#export TNS=cp4ba-wfps-baw-pfs-demo
#TNS=cp4ba-wfps-test-production
TNS=cp4ba-baw-authoring-bai-prod

# LDAP
export LDAP_DOMAIN=vuxdomain2
export LDAP_DOMAIN_EXT=net
export LDAP_FULL_DOMAIN="dc=${LDAP_DOMAIN},dc=${LDAP_DOMAIN_EXT}"
export LDAP_LDIF_NAME="./configs/_cfg2-ldap-domain.ldif"

# wait check interval
export LDAP_WAIT_SECS=10

# entitlement key (export CP4BA_AUTO_ENTITLEMENT_KEY in your shell before run the installation script)
export ENTITLEMENT_KEY=${CP4BA_AUTO_ENTITLEMENT_KEY}
